[project]
name = "a03-content-pipeline-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai[tools]>=0.152.0",
    "firecrawl>=4.3.6",
    "python-dotenv>=1.1.1",
]
